### PR TITLE
workspace: Adds rules to generate markdown docs

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
CC: @akirabaruah Let me know what you think of this, I think it might be really good to add this sort of thing into pigweed. It essentially just automagically generates markdown docs for your starlark files. I'm not sure how that would fit in with the existing sphinx-doc stuff that you have going on.

**Comment by akirabaruah** [comment]
Automatically generating docs from code sounds like the way to go. Pigweed currently uses restructured text, so we might have to pipe these markdown outputs into another translation rule (perhaps wrapping something like pandoc?). WDYT?

**Comment by silvergasp** [comment]
I'm not entirely sure, I think the docs in pigweed are handled with pandoc/sphinx but then managed by GN. So you'd almost want to call Bazel from GN to generate the markdown docs, then pipe that into sphinx/pandoc somehow. I'm not entirely sure how that would end up working though.

**Comment by akirabaruah** [comment]
Yeah, that might be the most straightforward way to integrate stardoc into the existing doc gen flow.

I suppose another option might be to require changes in Bazel BUILD files to commit intermediary docs that the GN build can use as is. The contributor (or automated tooling) could run these Bazel rules using just `bazel`, commit generated files, then have the existing GN system handle the rest. Would that make any sense?

**Comment by silvergasp** [comment]
Yeah, true that would make sense.

Any feedback on this PR? otherwise I'll probably merge it.

**Review by akirabaruah — APPROVED** [review]
Looks awesome. I'm wondering whether this change would supersede https://github.com/silvergasp/bazel_rules_cc_toolchain/pull/18.

**Comment by silvergasp** [comment]
> Looks awesome. I'm wondering whether this change would supersede #18.

I think it _will_ at some point, but actually going from docstrings->markdown to useful rendered docs is a little while off. I am working on it with [bazel_rules_zola](https://github.com/silvergasp/bazel_rules_zola) which just wraps a markdown generator. As an interim, #18 is more of an interim explanatory doc which is easy to view with Github's markdown rendering.

**Pull request merged**
